version: '3'

services:
    db:
        image: postgres
        volumes:
            - postgresvolume1:/var/lib/postgresql/data
        expose:
            - "5432"
        env_file: .env
    web:
        restart: always
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        env_file: .env
        volumes:
            - .:/myapp
        ports:
            - "3001:3001"
        depends_on: 
            - db

volumes:
    postgresvolume1: