default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  username: postgres
  password:
  timeout: 5000

development:
  <<: *default
  database: mooc_development

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
